spring.application.name=climalert
alertas.destinatarios=admin@clima.com,emergencias@clima.com,meteorologia@clima.com

# Interfaz de Programación de Aplicaciones (API) Externa
weather.api.url=http://api.weatherapi.com/v1/current.json
weather.api.key=${WEATHER_API_KEY}
weather.api.location=CABA

# Protocolo Simple de Transferencia de Correo (SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true